import bcrypt from 'bcryptjs';
const data={
    users:[
        {
            name:'Harry',
            email:'admin@example.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: true,
        },
        {
            name:'Jhon',
            email:'asdasff@example.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: false,
        },
        {
            name:"Tom",
            email:"abc@example.com",
            password:bcrypt.hashSync('1234',8),
            isAdmin:false,
            isSeller:true,
            seller:{
                name: 'Tom',
                logo: '/images/p1.jpg',
                description: 'excellent',
                rating: 4.5,
                numReviews: 10,
            }
       }
    ],
    products:[
        {
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Adidas Fit Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:100,
            countInStock:20,
            brand:'Nike',
            rating:4.0,
            numReviews:17,
            description:'high quality product',
        },
        {
            name:'Lacoste Free Pant',
            category:'Pants',
            image:'/images/p3.jpg',
            price:220,
            countInStock:50,
            brand:'Lacoste',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Nike Slim Pant',
            category:'Pants',
            image:'/images/p4.jpg',
            price:78,
            countInStock:0,
            brand:'Nike',
            rating:4.5,
            numReviews:14,
            description:'high quality product',
        },
        {
            name:'Puma Slim Shirt',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:65,
            countInStock:10,
            brand:'Puma',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Adidas Fit Pant',
            category:'Pants',
            image:'/images/p6.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },

    ],
};
export default data;